name: Build

on:
  schedule:
    # Every day at 9AM EST
    - cron:  '0 13 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh prometheusDhAlertMetricsStart.sh -d
      - name: Validate tables
        uses: deephaven/action-assert-dh-tables-present@v1.1.1
        with:
          table-names: prometheus_alerts,prometheus_metrics
          host: localhost
