name: Build

on:
  schedule:
    # Every day at 9AM EST
    - cron:  '0 13 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
           docker build --tag prometheus-deephaven/grpc-api .
           docker build --tag flask/prometheus-webhook-alerts flask-app
           docker-compose -f docker-compose.yml up -d
      - name: Validate tables
        uses: deephaven/action-assert-dh-tables-present@v1
        with:
          table-names: prometheus_alerts,prometheus_metrics
          host: localhost
